[tool.poetry]
name = "apexfinance"
version = "0.1.0"
description = ""
authors = ["Milad <milad.hz75@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
